
//Implementando desafio ORM O Liberal
### Create
POST http://localhost:3000/funcionarios
Content-Type: application/json

{
    "nome": "Joao",
    "cpf": "980.920.302-22",
    "carteira_trabalho":"777788",
    "setor": "Estoque",
    "telefones":["(91) 98157-0513","(91) 98157-0513"]
}

### FindAll
GET http://localhost:4444/funcionarios
Content-Type: application/json

### FindOne
GET http://localhost:4444/funcionarios/7
Content-Type: application/json


### Update
PUT http://localhost:4444/funcionarios/1
Content-Type: application/json

{
    "nome": "Fabricio Borges de Jesus",
    "cpf": "98092030211",
    "carteira_trabalho":"121651165165165161",
    "setor": "Escritório",
    "telefones":["91981570513","91982196666"]
}

### Delete
DELETE http://localhost:4444/funcionarios/1
Content-Type: application/json





//Testando requisicao recem criada
### Create

POST http://localhost:3000/users
Content-Type: application/json

{
    "email": "teste3@example.com",
    "nome": "Joao Davi de Jesus",
    "idade":8
}

### FindAll
GET http://localhost:3000/users
Content-Type: application/json

### FindOne
GET http://localhost:3000/users/1
Content-Type: application/json


### Update
PUT http://localhost:3000/users/1
Content-Type: application/json

{
    "email": "user@example.com",
    "nome": "Fabricio Siqueira de Jesus",
    "idade":34
}

### Delete
DELETE http://localhost:3000/users/1
Content-Type: application/json
