
//Implementando desafio ORM O Liberal
### Create
POST http://localhost:3000/funcionarios
Content-Type: application/json

{
    "nome": "Joao de Jesus",
    "cpf": "98092030222",
    "carteira_trabalho":"321651165165558889",
    "setor": "Estoque",
    "telefones":"[91981570513,91982192263,91982334455]"
}

### FindAll
GET http://localhost:3000/funcionarios
Content-Type: application/json

### FindOne
GET http://localhost:3000/funcionarios/1
Content-Type: application/json


### Update
PUT http://localhost:3000/funcionarios/1
Content-Type: application/json

{
    "nome": "Fabricio Borges de Jesus",
    "cpf": "98092030211",
    "carteira_trabalho":"121651165165165161",
    "setor": "Escritório",
    "telefones":"[91981570513,91982196666]"
}

### Delete
DELETE http://localhost:3000/funcionarios/1
Content-Type: application/json





//Testando requisicao recem criada
### Create

POST http://localhost:3000/users
Content-Type: application/json

{
    "email": "teste3@example.com",
    "nome": "Joao Davi de Jesus",
    "idade":8
}

### FindAll
GET http://localhost:3000/users
Content-Type: application/json

### FindOne
GET http://localhost:3000/users/1
Content-Type: application/json


### Update
PUT http://localhost:3000/users/1
Content-Type: application/json

{
    "email": "user@example.com",
    "nome": "Fabricio Siqueira de Jesus",
    "idade":34
}

### Delete
DELETE http://localhost:3000/users/1
Content-Type: application/json
